TOPDIR = ../..
-include $(TOPDIR)/config.mk

BIN = transaction.a
OBJS += check_conflicts.o
OBJS += check_replaces.o
OBJS += check_revdeps.o
OBJS += check_shlibs.o
OBJS += commit.o
OBJS += fetch.o
OBJS += files.o
OBJS += internalize.o
OBJS += ops.o
OBJS += pkg_deps.o
OBJS += prepare.o
OBJS += store.o

include $(TOPDIR)/mk/lib.mk