TOPDIR = ../..
-include $(TOPDIR)/config.mk

BIN = common.a
OBJS += cb_util.o  download.o  log.o    pubkey2fp.o  repo_sync.o  verifysig.o
OBJS += archive.o  conf.o     initend.o   pkgdb.o  proplib_wrapper.o   repo.o       rpool.o  

include $(TOPDIR)/mk/lib.mk