TOPDIR = ../..
-include $(TOPDIR)/config.mk

BIN = package.a
OBJS += alternatives.o
OBJS += config_files.o
OBJS += configure.o
OBJS += fulldeptree.o
OBJS += msg.o
OBJS += orphans.o
OBJS += register.o
OBJS += remove.o
OBJS += script.o
OBJS += state.o
OBJS += unpack.o

include $(TOPDIR)/mk/lib.mk